### ISSUE TITLE
PlayerTask infinite loop

### ISSUE THREAD

**Issue by AzGhort** [HearthSim/SabberStone#27]
I was trying to implement a simple RandomGreedyAI using Sabberstone:
![sabber](https://cloud.githubusercontent.com/assets/26720671/25446854/2d22391a-2ab3-11e7-8083-2a996af14be7.jpg)

I used it like that in a loop:
![sabber2](https://cloud.githubusercontent.com/assets/26720671/25446870/3bcf7b26-2ab3-11e7-8a9c-b6ba00d24bc4.jpg)

However, the games randomly loops inifinitely (usually on MinionAttackTasks), the player still produces Tasks, the game still processes them, but nothing happens... 
![capture8](https://cloud.githubusercontent.com/assets/26720671/25446929/75f37ce4-2ab3-11e7-9bf0-6cf8938ead9c.jpg)

Is there something I am missing in using CurrentPlayer.Options?
Thanks :)

**Comment by AzGhort** [comment]
I also reduced the inner while loops in second code, but it didn't help...

**Comment by darkfriend77** [comment]
Okay, looking at it ...

**Comment by citiral** [comment]
This seems to be caused by SabberStone generating invalid PlayerTasks, that abort while they are being run. If all playertasks (except for the endturn) are invalid, the AI will continually fail to execute tasks and get stuck in an infinite loop. I suggest Game.Process should return at least an eror code, telling us whether or not a tasks was successful. This would allow for a band-aid solution to be implemented in the AI, until all invalid tasks are fixed.

An example of an invalid task is Charged Devilsaur (Battlecry: Can't attack heroes this turn.) still getting a MinionAttackTask to attack the enemy hero. This fails when executing, since SabberStone checks for CANNOT_ATTACK_HEROES. All in all this AI will be really good to finding bugs like this! :)

**Comment by darkfriend77** [comment]
Charged Devilsaur is fixed ...
https://github.com/HearthSim/SabberStone/commit/b70d9642ccdfd43ef1bfe6eb76fdb4814ae71d80

but there are some more to fix

**Comment by AzGhort** [comment]
OK guys, thanks for your fast help :)

**Comment by darkfriend77** [comment]
I replicated your test more or less ... 

https://github.com/HearthSim/SabberStone/blob/master/SabberStoneCoreConsole/Program.cs

If it hangs now it dumps the game ....

**Comment by AzGhort** [comment]
Fine :) thanks!

**Comment by darkfriend77** [comment]
think that's good :-)
